name: pycaret

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 5 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Run black
        uses: psf/black@stable
        with:
          src: pycaret
      - name: Check imports
        uses: jamescurtin/isort-action@master
        with:
          sortPaths: pycaret

  # JOBS MUST START WITH test !!!!
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pytest
          python -m pip install -U codecov

          pip install -e ".[full]"
          if [ -f requirements-prophet.txt ]; then pip install -r requirements-prophet.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          python -m spacy download en_core_web_sm
      - name: Python version and dependency list
        run: |
          echo "Python version expected: ${{ matrix.python-version }}"
          python --version
          which python
          pip list
      - name: Remove tests
        run: |
          rm pycaret/tests/test_classification_tuning.py
          rm pycaret/tests/test_classification_plots.py
          rm pycaret/tests/test_regression_plots.py
          rm pycaret/tests/test_regression_tuning.py
          rm pycaret/tests/test_time_series_tune_grid.py
          rm pycaret/tests/test_time_series_tune_random.py
          rm pycaret/tests/test_time_series_plots.py
          rm pycaret/tests/test_time_series_utils_plots.py
      - name: Test with pytest
        run: |
          pytest

  test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pytest
          python -m pip install -U codecov

          pip install -e ".[full]"
          pip install -r requirements-prophet.txt
          pip install -r requirements-test.txt
          python -m spacy download en_core_web_sm
      - name: Python version and dependency list
        run: |
          echo "Python version expected: ${{ matrix.python-version }}"
          python --version
          which python
          pip list
      - name: Remove tests
        run: |
          remove-item pycaret/tests/* -Include @('test_classification_tuning.py','test_classification_plots.py','test_regression_plots.py', 'test_regression_tuning.py', 'test_time_series_tune_grid.py', 'test_time_series_tune_random.py', 'test_create_api.py', 'test_create_docker.py', 'test_drift_report.py', 'test_eda.py', 'test_time_series_plots.py', 'test_time_series_utils_plots.py')
      - name: Test with pytest
        run: |
          pytest

  # test_tuning:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -U pytest
  #       python -m pip install codecov
  #       pip install -e ".[full]"
  #       python -m pip install hpbandster ConfigSpace
  #       python -m spacy download en
  #   - name: Remove tests
  #     run: |
  #       find pycaret/tests -type f -not -name '__init__.py' -not -name 'test_classification_tuning.py' -not -name 'test_regression_tuning.py' -delete
  #   - name: Test with pytest
  #     run: |
  #       pytest -o log_cli=true

  # test_tuning_clf_windows:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -U pytest
  #       python -m pip install codecov
  #       pip install -e ".[full]"
  #       python -m spacy download en
  #   - name: Remove tests
  #     run: |
  #       remove-item pycaret/tests/* -Exclude @('__init__.py','test_classification_tuning.py')
  #   - name: Test with pytest
  #     run: |
  #       pytest -o log_cli=true

  # test_tuning_reg_windows:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -U pytest
  #       python -m pip install codecov
  #       pip install -e ".[full]"
  #       python -m spacy download en
  #   - name: Remove tests
  #     run: |
  #       remove-item pycaret/tests/* -Exclude @('__init__.py','test_regression_tuning.py')
  #   - name: Test with pytest
  #     run: |
  #       pytest -o log_cli=true

  test_plots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U pytest
          python -m pip install codecov
          pip install -e ".[full]"
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          python -m spacy download en_core_web_sm
      - name: Python version and dependency list
        run: |
          echo "Python version expected: ${{ matrix.python-version }}"
          python --version
          which python
          pip list
      - name: Remove tests
        run: |
          find pycaret/tests -type f -not -name '__init__.py' -not -name 'test_classification_plots.py' -not -name 'test_regression_plots.py' -not -name 'conftest.py' -not -name 'time_series_test_utils.py' -not -name 'test_time_series_plots.py' -not -name 'test_time_series_utils_plots.py' -delete
      - name: Test with pytest
        run: |
          pytest -o log_cli=true

  test_ts_tune_random:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pytest
          python -m pip install -U codecov

          pip install -e ".[full]"
          if [ -f requirements-prophet.txt ]; then pip install -r requirements-prophet.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

          python -m spacy download en_core_web_sm
      - name: Python version and dependency list
        run: |
          echo "Python version expected: ${{ matrix.python-version }}"
          python --version
          which python
          pip list
      - name: Remove tests
        run: |
          find pycaret/tests -type f -not -name '__init__.py' -not -name 'conftest.py' -not -name 'time_series_test_utils.py' -not -name 'test_time_series_tune_random.py' -delete
      - name: Test with pytest
        run: |
          pytest -o log_cli=true

  test_ts_tune_grid:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U pytest
          python -m pip install -U codecov

          pip install -e ".[full]"
          if [ -f requirements-prophet.txt ]; then pip install -r requirements-prophet.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

          python -m spacy download en_core_web_sm
      - name: Python version and dependency list
        run: |
          echo "Python version expected: ${{ matrix.python-version }}"
          python --version
          which python
          pip list
      - name: Remove tests
        run: |
          find pycaret/tests -type f -not -name '__init__.py' -not -name 'conftest.py' -not -name 'time_series_test_utils.py' -not -name 'test_time_series_tune_grid.py' -delete
      - name: Test with pytest
        run: |
          pytest -o log_cli=true
